#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdc, 2014-05-04 15:42:54 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *          Example of how to run Rdc of DAMPE
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcEQM as DmpRdcAlg

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.SetMaxEventNumber(1000)
DMPSW.Core.SetLogLevel(1111)      # If NOT set, will use 1100
'''
  /*
   * LogLevel
   *     types: {error(1000) | warning(100) | information(10) | debug(1)}
   */
'''
#DMPSW.Core.SetTimeWindow("start",2013,1,1,0,0,0)       # if NOT set, start from 0 second
#DMPSW.Core.SetTimeWindow("stop",2016,1,1,0,0,0)        # if NOT set, end at 2113.01.01

#-------------------------------------------------------------------
# IOSvc options
DMPSW.IOSvc.Set("OutData/Path","./test")    # where to save the output. If NOT set will use "./" by defualt
DMPSW.IOSvc.Set("OutData/Tag","Rdc")    # append note for the next output data. NOT set is okay. Also could use Set("OutDataPath")

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgEQM = DmpRdcAlg.DmpRdcAlgEQM()
rdcAlgEQM.Set("Psd/Connector",DMPSW.prefix+"/share/Connector/Bgo/EQM")
#rdcAlgEQM.Set("Stk/Connector",DMPSW.prefix+"/share/Connector/Bgo/EQM")
rdcAlgEQM.Set("Bgo/Connector",DMPSW.prefix+"/share/Connector/Bgo/EQM")
rdcAlgEQM.Set("Nud/Connector",DMPSW.prefix+"/share/Connector/Bgo/EQM")
rdcAlgEQM.Set("BinaryFile",DMPSW.prefix+"/share/TestRelease/Ex_BGO_ScienceData_20121002212322.dat")
rdcAlgEQM.Set("BinaryFile",DMPSW.prefix+"/share/TestRelease/Ex_Data_20140417235702_BGO_20140418-000421.bin")

#-------------------------------------------------------------------
#rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
#rdcDataMgr.Set("InData","/home/zhzhy/CombinedRun_Nanjing201404/Data_2014_4_17_23_57_02_BGO_20140418-000421.bin")
#-------------------------------------------------------------------

# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgEQM)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialise()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


