#! /bin/bash
#=============================================================================
#       FileName :          dmpsw-config
#       Version  :          0.0.1
#       Author   :          Chi Wang (chiwang@mail.ustc.edu.cn)
#       Time     :          2013-07-30   01:15:10
#
#------------------------------------------------------------------------------
#       Description  :
#           *   need to modify version ID before publish
#           *   must in /prefix/bin
#------------------------------------------------------------------------------
#       History  :
#                                          Update:  2013-09-30   16:59:13
#=============================================================================

#   set version before release  *********
version=1.0.0

#   check path
PWD=`pwd`
if [[ ! "$PWD" =~ "bin" ]];then
  echo "$0 must in /InstallPath/bin/"
  exit
else
  prefix=$PWD/..
fi

#   list all libraries of DmpSW
libs=""
for file in `ls ${prefix}/lib`;do
  if [[ ${file} = *libDmp* && ${file} = *.so* ]];then
    file=${file/lib/-l}
    file=${file/\.so/}
    libs="$libs $file"
  fi
done

#-----------------------------------------------------------------------
# function help
#          print help on available command line arguments and enabled

help()
{
  cat<<EOF

Usage: dmpsw-config [OPTION...]

  --prefix                output installation prefix of DAMPE Software
  --version               output version for DAMPE Software
  --libs                  output all linker flags
  --cflags                output all preprocessor and compiler flags
  --help                  output help information

EOF

  exit 1
}


#-----------------------------------------------------------------------
# output
#       will be used while using DAMPE software.

out=""

while test $# -gt 0; do
  case "$1" in
    -*=*)
      optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
      ;;
    *)
      optarg=
      ;;
  esac

  case $1 in
    --prefix)
      out="$out $prefix"
      ;;
   --libs)
      out="$out -L$prefix/lib $libs"
      ;;
   --cflags)
      out="$out -I$prefix/include"
      ;;
   -?)
      help
      ;;
   --help)
      help
      ;;
   --version)
      out="DampeSW verison $version"
      ;;
  esac
  shift
done

### Output the stuff
echo $out


