
// *
// *  TODO: Event
//
//      1.  save vector(fRunMode) wrong, fix it
//      2.  add digitization into EventAction.cc
//      3.  add PrintTime() in order to check time in Rdc
// *

// *
// *  TODO: Geometry
//
//      1.  Scons file
//      2.  schema files
//      3.  all phase gdml file
// *

// *
// *  TODO: Simulation
//
//      (X)1.  check run script
//      2.  add phase monitor, and then read gdml files automaticaly
// *


// *
// *  TODO: Rdc
//
//      1.  JobOpt file
//      2.  Bgo part Conversion
//      3.  ConvertEventHeader()
//      4.  does it necessary to SetConnector Path in python ??
// *


