#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcBT2012, 2014-05-29 11:03:06 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. BT2012
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcBT2012 as DmpRdcAlg

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.SetMaxEventNumber(100)  # If NOT set, will use 1234567890
DMPSW.Core.SetLogLevel("Debug",1)      # Option = {Error | Warning | Info | Debug}. If NOT set, will use Info.
#DMPSW.Core.SetTimeWindow("start",2013,1,1,0,0,0)       # if NOT set, start from 0 second
#DMPSW.Core.SetTimeWindow("stop",2016,1,1,0,0,0)        # if NOT set, end at 2113.01.01

#-------------------------------------------------------------------
# IOSvc Service
DMPSW.IOSvc.Set("OutData/Path","./test")      # where to save the output. If NOT set will use "./" by defualt
DMPSW.IOSvc.Set("OutData/Tag","Rdc")    # append note for the next output data. NOT set is okay. Also could use Set("OutDataPath")

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = DmpRdcAlg.DmpRdcAlgBT2012()
rdcAlgBT.Set("Psd/Connector",DMPSW.prefix+"/share/Connector/Bgo/EM")
#rdcAlgBT.Set("Stk/Connector",DMPSW.prefix+"/share/Connector/Bgo/EM")
rdcAlgBT.Set("Bgo/Connector",DMPSW.prefix+"/share/Connector/Bgo/EM")
rdcAlgBT.Set("Nud/Connector",DMPSW.prefix+"/share/Connector/Bgo/EM")
rdcAlgBT.Set("BinaryFile",DMPSW.prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
#rdcAlgBT.Set("BinaryFile",DMPSW.prefix+"/share/TestRelease/Ex_BGO_ScienceData_20121002212322.dat")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialise()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

