#=====================================================================
#   File:   SConstruct
#   Author: Chi WANG  (chiwang@mail.ustc.edu.cn)    24/07/2013
#---------------------------------------------------------------------
#   Description:
#
#   *** Default degub=0, scons debug=1 will create in debug mode
#         means: create all thing in current directory instead of install into /prefix
#
#   1.  Root
#       ARGUMENTS.get('root',value):
#           value = 1,      use root
#           scons root=0,   not use
#   2.  Geant4
#         ARGUMENTS.get('g4',value):
#           value = 0,      not use geant4
#           scons g4=1,     use geant4
#   3.  OpenMP
#         ARGUMENTS.get('omp',value):
#           value = 0,      not use OpenMP
#           scons omp=1,    use it
#
#---------------------------------------------------------------------
#   History:
#                           Last update:  13/12/2013   12:22:48
#=====================================================================

print "\n\t\t--->building Event module"

import os
EnvEvt = Environment(ENV = os.environ)

#   set the programme name
LibName='DmpEvent'

#   set debug modle.
#    if yes, then can use gdb:  http://www.ibm.com/developerworks/cn/linux/sdk/gdb/
debug=ARGUMENTS.get('debug',1)
if int(debug):
    print "\t\t debug mode"
    EnvEvt.Prepend(CCFLAGS = '-g')
    EnvEvt.Append(CCFLAGS = '-DDmp_DEBUG')
    installdir=os.environ['DMPSWWORK']
else:
    EnvEvt.Append(CCFLAGS = '-DDmp_RELEASE')
    Import('PREFIX')
    installdir=PREFIX

#   set Geant4 environment
if int(ARGUMENTS.get('g4',0)):
    g4sys=os.environ['G4INSTALL']
    EnvEvt.PrependENVPath('PATH', g4sys+'/../../../bin')
    EnvEvt.ParseConfig("geant4-config --cflags --libs")

#   set Root environment
if int(ARGUMENTS.get('root',1)):
    EnvEvt.ParseConfig("root-config --cflags --libs")

#   set OpenMP
if int(ARGUMENTS.get('omp',0)):
    LibName=LibName+"_omp"
    EnvEvt.MergeFlags('-fopenmp')

#   include
for key in ['Psd','Stk','Bgo','Nud']:
    includeDir=key+'/include'
    if int( not debug):
        for file in os.listdir(includeDir):
            Default(Command(PREFIX+'/include/'+file,includeDir+'/'+file,Copy("$TARGET","$SOURCE")))
    EnvEvt.Prepend(CPPPATH=[includeDir])

#   Use other top-1 package
    #+  Kernel
P1Path='../Kernel'
EnvEvt.Prepend(CPPPATH=[P1Path+'/include'])

#   main build
execute=EnvEvt.SharedLibrary(LibName,Glob('./*/src/*.cc'))
Default(EnvEvt.InstallAs(installdir+"/lib/lib"+LibName+".so",execute))


