#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcBT2012, 2014-06-29 23:16:04 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. BT2012
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcBT2012 as DmpRdcAlg

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.Set("EventNumber","100")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc Service
#DMPSW.RootIOSvc.Set("InData/Update","DmpRdcData.root")        # save output into input root file, if you really need
DMPSW.RootIOSvc.Set("OutData/FileName","./test/DmpRdcData.root")        # must set it, if NOT set, will not save anything
DMPSW.RootIOSvc.Set("OutData/Write","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = DmpRdcAlg.DmpRdcAlgBT2012()
#rdcAlgBT.Set("Psd/Connector",DMPSW.SysPath+"/share/Connector/Psd/EM")
#rdcAlgBT.Set("Stk/Connector",DMPSW.SysPath+"/share/Connector/Stk/EM")
rdcAlgBT.Set("Bgo/Connector",DMPSW.SysPath+"/share/Connector/Bgo/EM")
#rdcAlgBT.Set("Nud/Connector",DMPSW.SysPath+"/share/Connector/Nud/EM")
#rdcAlgBT.Set("BinaryFile",DMPSW.SysPath+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
rdcAlgBT.Set("BinaryFile",DMPSW.SysPath+"/share/TestRelease/Ex_BGO_ScienceData_20121002212322.dat")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


