#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdc, 2014-04-25 15:57:36 DAMPE/USTC $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *          Example of how to run Rdc of DAMPE
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
# Load lib. of DAMPE software
import os
import sys
sys.setdlopenflags(0x100|0x2)
import libDmpCore as DmpCore
import libDmpRdc as  DmpRdc

prefix=os.getenv('DMPSWSYS')
#-------------------------------------------------------------------
# Create Service
rdcDataMgr = DmpRdc.DmpRdcSvcDataMgr()
rdcDataMgr.Set("OutDataPath","./test")      # where to save the output. If NOT set will use "./" by defualt
rdcLog = DmpRdc.DmpRdcSvcLog()
rdcLog.Set("Log/Level","1")                 # 0: nothing. 1: error infor. >1 everything

#-------------------------------------------------------------------
# Create Algorithm
rdcAlgHed = DmpRdc.DmpRdcAlgHeader("RdcAlgHeader")
rdcAlgPsd = DmpRdc.DmpRdcAlgPsd()
rdcAlgNud = DmpRdc.DmpRdcAlgNud()
rdcAlgBgo = DmpRdc.DmpRdcAlgBgo()
rdcAlgStk = DmpRdc.DmpRdcAlgStk()
rdcAlgPsd.Set("CnctPath",prefix+"/share/Connector/Psd/Quarter")
rdcAlgNud.Set("CnctPath",prefix+"/share/Connector/Nud/Quarter")
rdcAlgBgo.Set("CnctPath",prefix+"/share/Connector/Bgo/Quarter")
rdcAlgStk.Set("CnctPath",prefix+"/share/Connector/Stk/Quarter")

#-------------------------------------------------------------------
# RUN DmpCore
    ##  Service Manager
gDmpSvcMgr = DmpCore.DmpServiceManager.GetInstance()
gDmpSvcMgr.Append(rdcDataMgr)
gDmpSvcMgr.Append(rdcLog)
gDmpSvcMgr.Initialize()
    ##  Algorithm Manager (Append order is important)
gDmpAlgMgr = DmpCore.DmpAlgorithmManager.GetInstance()
gDmpAlgMgr.Append(rdcAlgHed)
gDmpAlgMgr.Append(rdcAlgNud)
gDmpAlgMgr.Append(rdcAlgPsd)
gDmpAlgMgr.Append(rdcAlgBgo)
#gDmpAlgMgr.Append(rdcAlgStk)
gDmpAlgMgr.Initialize()

#-------------------------------------------------------------------
# Run job
    ##  Start to run this job (Execute()). Also could use Set("outDataPath") between 2 Execute()
rdcDataMgr.Set("OutDataNote","ProTest")   # set tag for the next output data. NOT set is okay
#rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_Data_20140417235702_BGO_20140418-000421.bin")
DmpRdc.Execute()
#rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
#DmpRdc.Execute()

#-------------------------------------------------------------------
# Quit DmpCore
gDmpAlgMgr.Finalize()


