#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdc, 2014-03-22 02:52:03 chi $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *          Example of how to run Rdc of DAMPE
 *-----------------------------------------------------
'''

# load lib. of DAMPE software
import os
import sys
prefix=os.getenv('DMPSWSYS')
if os.environ['DMPSWSYS'] not in sys.path:
    sys.path.append(prefix+'/lib')

import libDmpCore as DmpCore
import libDmpRdc as  DmpRdc

# RUN Raw Data Conversion
    ##  where to save the output. If NOT set will use "./" by defualt
gRdcDataMgr = DmpRdc.DmpRdcDataManager.GetInstance()
gRdcDataMgr.SetOutDataPath("./test")
    ##  where to read cnct files for different subDet
gRdcCnctMgr = DmpRdc.DmpRdcCnctPath.GetInstance()
gRdcCnctMgr.SetConnectorPath(DmpCore.DmpEDetectorID.kPsd,prefix+"/share/Connector/Psd/Quarter")
#gRdcCnctMgr.SetConnectorPath(DmpCore.DmpEDetectorID.kStk,prefix+"/share/Connector/Stk/Quarter")     # if NOT set, will skip setupconnector and conversion methods of this subDet.
gRdcCnctMgr.SetConnectorPath(DmpCore.DmpEDetectorID.kBgo,prefix+"/share/Connector/Bgo/Quarter")
gRdcCnctMgr.SetConnectorPath(DmpCore.DmpEDetectorID.kNud,prefix+"/share/Connector/Nud/Quarter")

    ##  Start Rdc. ORDER: Initialize(), then Execute(), finally Clear(). Also could use SetOutDataPath() between different Execute()
DmpRdc.Initialize()      # create Rdc argorithm of all subDet, and setup connectors
gRdcDataMgr.AppendDataNote("protonTest")        # set tag for the next output data. NOT set is okay
#DmpRdc.Execute(prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
DmpRdc.Execute(prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")     # Trigger match level(with Bgo) 1: Psd; 2(or 3): Psd, Stk; 4: Psd, Stk, Nud
DmpRdc.Clear()


