/gps/source/clear 

/gps/source/add 1  
#/gps/particle e- 
/gps/particle proton
/gps/pos/type Plane 
/gps/pos/shape Square
/gps/pos/centre 10. 10. -360.0 mm
/gps/pos/halfx 0.02475 mm
/gps/pos/halfy 0.02475 mm
/gps/ang/type cos 
/gps/ang/mintheta 0.00 deg 
/gps/ang/maxtheta 0.0010 deg
/gps/ene/type Lin 
/gps/ene/min 150. GeV 
/gps/ene/max 150.00000001 GeV 
/gps/ene/gradient 0. 
/gps/ene/intercept 1.

/run/beamOn 500

