#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpSim, 2014-03-18 10:32:38 chi $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 07/03/2014
 *-----------------------------------------------------
 *  This is an example how to run simulation of DAMPE
 *-----------------------------------------------------
'''

# load lib. of DAMPE software
import os
import sys
prefix=os.getenv('DMPSWSYS')
if os.environ['DMPSWSYS'] not in sys.path:
    sys.path.append(prefix+'/lib')

import libDmpCore as DmpCore
import libDmpSim as  DmpSim

# RUN simulation
    ##  where to save the output. If NOT set will use "./" by defualt
simDataMgr = DmpSim.DmpSimDataManager.GetInstance()
simDataMgr.SetOutDataPath("./test")
    ##  where to read gdml files for different subDet, if NOT set will ignore this subDet.
simDetPar = DmpSim.DmpSimDetectorInterface.GetInstance()
simDetPar.SetGdmlPath(DmpCore.DmpEDetectorID.kWhole,prefix+"/share/Geometry/Sat/Quarter")      # must add satellite gdml files
#simDetPar.SetGdmlPath(DmpCore.DmpEDetectorID.kPsd,prefix+"/share/Geometry/Psd/Quarter")
#simDetPar.SetGdmlPath(DmpCore.DmpEDetectorID.kStk,prefix+"/share/Geometry/Stk/Quarter")       # if NOT set, will not construct this subDet
simDetPar.SetGdmlPath(DmpCore.DmpEDetectorID.kBgo,prefix+"/share/Geometry/Bgo/Quarter")
#simDetPar.SetGdmlPath(DmpCore.DmpEDetectorID.kNud,prefix+"/share/Geometry/Nud/Quarter")
#simDetPar.SetOffset(DmpCore.DmpEDetectorID.kPsd,-80)            # Reset offset if you like

    ##  Start simulation. ORDER: Initialize(), then Execute(), finally Clear(). Also could use SsetIn(Out)DataPath() between different Execute()
DmpSim.Initialize()      # setup detector, user actions
for i in range(4):
    DmpSim.Execute(prefix+"/share/TestRelease/Ex_electron.mac")
#simDataMgr.SetOutDataTag("protonTest")        # set tag for the next output data which will be created in the next Execute(). If NOT set is okay
#DmpSim.Execute(prefix+"/share/TestRelease/Ex_proton.mac")     # start a new run, without delete physics list, detector construction and all user actions.
#DmpSim.Execute("visual")                # open visual mode, if you don't want to use batch mode as above(input a macro file name in Execute()).
DmpSim.Clear()


