#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpSimulation, 2014-03-08 13:08:19 chi $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 07/03/2014
 *-----------------------------------------------------
 *  This is an example how to run simulation of DAMPE
 *-----------------------------------------------------
'''

# load lib. of DAMPE software
import os
import sys
if os.environ['DMPSWSYS'] not in sys.path:
    sys.path.append(os.getenv('DMPSWSYS')+'/lib')

import libDmpCore as DmpCore
import libDmpSimulation as DmpSimulation


# set output file path. 
DmpCore.DataManager.SetOutDataPath("./test")    # Use "./" as default path if NOT set at here

# RUN simulation
DmpSimulation.Initialize()
#DmpSimulation.Execute("default")   # visual mode
DmpSimulation.Execute("electron.mac")
DmpCore.DataManager.SetOutDataName("electron.root") # set the name of outdata (*.root) for the next Execute() instead of using the default name(time related)
DmpSimulation.Execute("electron.mac")
DmpSimulation.Execute("proton.mac")  # keep detector and all user action, and run next macro file
DmpSimulation.Clear()

