#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcBgoEQM, 2014-06-30 02:05:08 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *          Example of how to run Rdc of DAMPE
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpAlgBgoRdcEQM as DmpRdcAlg

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.Set("EventNumber","20")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.Set("InData/Update","DmpRdcData.root")        # save output into input root file, if you really need
DMPSW.RootIOSvc.Set("OutData/FileName","./test/DmpRdcData.root")        # must set it, if NOT set, will not save anything
DMPSW.RootIOSvc.Set("OutData/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcBgoEQM = DmpRdcAlg.DmpAlgBgoRdcEQM()
rdcBgoEQM.Set("BinaryFile","./Ex_Data_20140417235702_BGO_20140418-000421.bin")
rdcBgoEQM.Set("Connector",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcBgoEQM)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

