#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcBT2012, 2014-05-04 15:45:37 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. BT2012
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
# Load lib. of DAMPE software
import os
import sys
sys.setdlopenflags(0x100|0x2)
import libDmpKernel as DmpKernel
import libDmpRdcSvc as DmpRdcSvc
import libDmpRdcBT2012 as DmpRdcAlg

prefix=os.getenv('DMPSWSYS')
dmpCore = DmpKernel.DmpCore.GetInstance()
dmpSvcMgr = dmpCore.ServiceManager()
dmpAlgMgr = dmpCore.AlgorithmManager()
dmpCore.SetLogLevel(0)      # If NOT, will use 12
'''
  /*
   * LogLevel
   *     types: {error(8) | warning(4) | information(2) | debug(1)}
   *    0:      nothing
   *    1:      debug
   *    2:      infor.
   *    3:      debug + infor.
   *    4:      warning
   *    5:      warning + debug
   *    6:      warning + infor.
   *    7:      warning + infor. + debug
   *    8:      error
   *    9:      error + debug
   *    10:     error + infor.
   *    11:     error + infor. + debug
   *    12:     error + warning
   *    13:     error + warning + debug
   *    14:     error + warning + infor.
   *    15:     error + warning + infor. + debug
   */
'''
#dmpCore.SetTimeWindow("start",2013,1,1,0,0,0)       # if NOT set, start from 0 second
#dmpCore.SetTimeWindow("stop",2016,1,1,0,0,0)        # if NOT set, end at 2113.01.01

#-------------------------------------------------------------------
# Create Service
rdcDataMgr = DmpRdcSvc.DmpRdcSvcDataMgr()
rdcDataMgr.Set("OutDataPath","./test")      # where to save the output. If NOT set will use "./" by defualt

#-------------------------------------------------------------------
# Create Algorithm
rdcAlgHed = DmpRdcAlg.DmpRdcAlgHeader()
rdcAlgPsd = DmpRdcAlg.DmpRdcAlgPsd()
rdcAlgNud = DmpRdcAlg.DmpRdcAlgNud()
rdcAlgBgo = DmpRdcAlg.DmpRdcAlgBgo()
#rdcAlgStk = DmpRdcAlg.DmpRdcAlgStk()
rdcAlgPsd.Set("CnctPath",prefix+"/share/Connector/Psd/EM")
rdcAlgNud.Set("CnctPath",prefix+"/share/Connector/Nud/EM")
rdcAlgBgo.Set("CnctPath",prefix+"/share/Connector/Bgo/EM")
#rdcAlgStk.Set("CnctPath",prefix+"/share/Connector/Stk/EM")

#-------------------------------------------------------------------
# Set service and algorithm into Kernel
    ##  Service Manager
dmpSvcMgr.Append(rdcDataMgr)
    ##  Algorithm Manager (Append order is important)
dmpAlgMgr.Append(rdcAlgHed)
dmpAlgMgr.Append(rdcAlgNud)
dmpAlgMgr.Append(rdcAlgPsd)
dmpAlgMgr.Append(rdcAlgBgo)
#dmpAlgMgr.Append(rdcAlgStk)

#-------------------------------------------------------------------
# Boot
dmpCore.Initialize()

#-------------------------------------------------------------------
# Run job
    ##  Start to run this job (Execute()). Also could use Set("outDataPath") between 2 Execute()
rdcDataMgr.Set("OutDataNote","ProTest")   # set tag for the next output data. NOT set is okay
rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
#rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_Data_20140417235702_BGO_20140418-000421.bin")
#rdcDataMgr.Set("InData","/home/zhzhy/CombinedRun_Nanjing201404/Data_2014_4_17_23_57_02_BGO_20140418-000421.bin")
DmpRdcSvc.Execute()
#rdcDataMgr.Set("InData",prefix+"/share/TestRelease/Ex_ScienceData_20121005164959.dat")
#DmpRdc.Execute()

#-------------------------------------------------------------------
# Quit
dmpCore.Finalize()


