'''
 *  $Id: SConstruct, 2014-04-26 20:51:42 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 23/09/2013
 *----------------------------------------------------------
 *  1. create a shared library
 *  2. install it into $DMPSWWORK
 *  then, in your JobOpt* file could use your Alg.
 *----------------------------------------------------------
'''

import os

target='DmpRdcBT2012'

print "---> compiling: %s\n" % target
#--------------------------------------------------------------------
# environment
env = Environment(ENV = os.environ)
env.ParseConfig("dmpsw-config --cflags --libs")
env.ParseConfig("python-config --include --libs")  # 2 lines for binding
env.Append(LIBS=['boost_python'])
env.ParseConfig("root-config --cflags --libs")
#env.ParseConfig("clhep-config --include --libs")
#env.PrependENVPath('PATH', os.environ['G4INSTALL']+'/../../../bin')    # 2 lines for G4
#env.ParseConfig("geant4-config --cflags --libs")
#env.MergeFlags('-fopenmp')

#-------------------------------------------------------------------
# include dir. and external libs
env.Prepend(CPPPATH=['./include'])
# Add boost filesyetem
#env.Append(LIBS=['boost_filesystem-mt'])

#-------------------------------------------------------------------
# main build
goal=env.SharedLibrary(target,Glob('./src/*.cc'))
Default(env.InstallAs(os.environ['DMPSWWORK']+'/lib/lib'+target+".so",goal))

